### ISSUE TITLE
Suggestion - regarding the IP in settings.txt

### ISSUE THREAD

**Issue by STEFnr1** [Project-Genoa/Vienna-docker#2]
Users might want to associate Vienna to work with a domain with a SSL Certificate. However, if they want to, the URL given for the API, CDN etc will be http://, no matter what the user puts in the address field in settings.txt. Here's how I think this would work best:

if the user puts the protocol in front on the IP address/domain, Vienna will use that instead of the default
if the user uses an IP Address/domain with no protocol in front, the default, http://, will be used.

At the moment, even if you put in the address field "https://domain.name/", the locator will return addresses like "http://https://domain.name/".

**Comment by micheal65536** [comment]
You are correct, the `settings.txt` file only allows HTTP. There is a good reason for this:

1. Vienna itself only supports HTTP. In order to use HTTPS it is necessary to run it behind an HTTPS reverse proxy. (This is typical of many web apps/services.)

2. This repository is designed to be as foolproof as possible to set up for people without much technical knowledge. You would be surprised how many people will incorrectly put HTTPS as the protocol and then complain/get stuck when it doesn't work.

However, Vienna is packaged as a set of Docker containers, so it is very easy for more technical users to configure and deploy it however they want. You can change the `docker-compose.yml` file to suit your particular setup, including changing the address and protocol returned by the locator server and adding your HTTPS reverse proxy (e.g. Nginx) into the same Compose configuration.

As Vienna won't work with HTTPS without additional setup anyway, there is no reason to support HTTPS in the `settings.txt` file. Anyone who is technically advanced enough to be using HTTPS should not be using the `settings.txt` file for configuration and should be writing/modifying their own Compose file.
